### ISSUE TITLE
Did not work with nuxt.js

### ISSUE THREAD

**Issue by PhilAndrew** [nikolaynesov/vue-body-class#7]
Tried to get it to work.

Get this error.

Nuxt.js Error:

```
ReferenceError: document is not defined
    at VueBodyClassController.init (C:\home\projects\ContractPen\contractpenweb\node_modules\vue-body-class\dist\index.js:19:30)
    at VueBodyClassController.VueBodyClass.install (C:\home\projects\ContractPen\contractpenweb\node_modules\vue-body-class\dist\index.js:119:18)
    at Function.Vue.use (C:\home\projects\ContractPen\contractpenweb\node_modules\vue\dist\vue.runtime.common.js:3866:22)
    at Object.module.exports.Object.defineProperty.value (src-nuxt/plugins/BodyClass.js:4:4)
    at __webpack_require__ (webpack:/webpack/bootstrap 607ec30d15c914834ee1:25:0)
    at Object.module.exports.module.exports.list (.nuxt/index.js:88:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 607ec30d15c914834ee1:25:0)
    at Object.<anonymous> (server-bundle.js:2054:65)
    at __webpack_require__ (webpack:/webpack/bootstrap 607ec30d15c914834ee1:25:0)
    at module.exports.module.exports.version (webpack:/webpack/bootstrap 607ec30d15c914834ee1:93:0)
    at Object.<anonymous> (server-bundle.js:98:10)
    at evaluateModule (C:\home\projects\ContractPen\contractpenweb\node_modules\vue-server-renderer\build.js:6967:21)
    at C:\home\projects\ContractPen\contractpenweb\node_modules\vue-server-renderer\build.js:6985:15
    at C:\home\projects\ContractPen\contractpenweb\node_modules\vue-server-renderer\build.js:6983:12
    at Nuxt.renderToString (C:\home\projects\ContractPen\contractpenweb\node_modules\vue-server-renderer\build.js:7106:9)
    at C:\home\projects\ContractPen\contractpenweb\node_modules\pify\index.js:29:7
```

**Comment by PhilAndrew** [comment]
Doesn't matter, nuxt has a way. https://github.com/nuxt/nuxt.js/issues/188

**Comment by nikolaynesov** [comment]
@PhilAndrew thanks, the solution you mentioned was added to the doc for Nuxt.js.
